name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ngx_wasm
        uses: actions/checkout@v4

      - name: Checkout nginx
        uses: actions/checkout@v4
        with:
          repository: nginx/nginx
          path: nginx

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            clang-format \
            perl \
            cpanminus \
            curl \
            xz-utils

      - name: Fetch pinned project dependencies
        run: make deps

      - name: Check formatting
        run: make check-format

      - name: Build
        run: make build NGINX_DIR="${GITHUB_WORKSPACE}/nginx" NGINX_BUILD_JOBS=2

      - name: Build ASan+UBSan variant
        if: runner.os == 'Linux'
        run: make build BUILD_SANITIZE=1 NGINX_DIR="${GITHUB_WORKSPACE}/nginx" NGINX_BUILD_JOBS=2

      - name: Run Test::Nginx suite
        if: runner.os == 'macOS'
        run: make test NGINX_DIR="${GITHUB_WORKSPACE}/nginx"

      - name: Run ASan+UBSan Test::Nginx suite
        if: runner.os == 'Linux'
        run: make test NGINX_DIR="${GITHUB_WORKSPACE}/nginx"
